"""Builds db/setup_plain_postgres.sql from supabase/setup_fresh_database.sql.

For a plain PostgreSQL server (no Supabase): adds a minimal `auth.users` table,
and drops Supabase-only statements (RLS policies for the authenticated /
service_role roles, grants to those roles, storage bucket setup). The API
enforces access control itself, so nothing is lost.

    python3 db/build_plain_postgres.py
"""
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
src = (root / 'supabase/setup_fresh_database.sql').read_text()

def statements(sql: str):
    """Split on ; outside $$ blocks and string literals."""
    out, buf, i, in_dollar, in_str = [], [], 0, False, False
    while i < len(sql):
        if sql.startswith('$$', i) and not in_str:
            in_dollar = not in_dollar; buf.append('$$'); i += 2; continue
        ch = sql[i]
        if ch == "'" and not in_dollar:
            in_str = not in_str
        if ch == ';' and not in_dollar and not in_str:
            out.append(''.join(buf) + ';'); buf = []
        else:
            buf.append(ch)
        i += 1
    if ''.join(buf).strip():
        out.append(''.join(buf))
    return out

def keep(stmt: str) -> bool:
    body = re.sub(r'--[^\n]*', '', stmt).strip().upper()
    if not body:
        return True
    if body.startswith(('CREATE POLICY', 'DROP POLICY', 'GRANT ')):
        return False
    if 'STORAGE.' in body:
        return False
    if body.startswith('ALTER TABLE') and 'ROW LEVEL SECURITY' in body:
        return False
    return True

prelude = """-- ============================================================
-- GENERATED by db/build_plain_postgres.py — do not edit by hand.
-- Schema for a plain PostgreSQL server (no Supabase).
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Minimal user table replacing Supabase's auth.users.
CREATE SCHEMA IF NOT EXISTS auth;
CREATE TABLE IF NOT EXISTS auth.users (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email         TEXT        NOT NULL UNIQUE,
  password_hash TEXT,
  full_name     TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_sign_in_at TIMESTAMPTZ
);
CREATE OR REPLACE FUNCTION auth.uid() RETURNS UUID LANGUAGE SQL STABLE AS $$ SELECT NULL::UUID $$;

"""
# Comments can contain apostrophes that would confuse the splitter.
src = re.sub(r'--[^\n]*', '', src)
body = '\n'.join(s.strip() for s in statements(src) if keep(s) and s.strip(' \n;'))
body = re.sub(r'\n{3,}', '\n\n', body)
body = body.replace('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";', '')
(root / 'db/setup_plain_postgres.sql').write_text(prelude + body)
print('wrote db/setup_plain_postgres.sql')
