-- ============================================================
-- GENERATED by db/build_plain_postgres.py — do not edit by hand.
-- Schema for a plain PostgreSQL server (no Supabase).
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Minimal user table replacing Supabase's auth.users.
CREATE SCHEMA IF NOT EXISTS auth;
CREATE TABLE IF NOT EXISTS auth.users (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email         TEXT        NOT NULL UNIQUE,
  password_hash TEXT,
  full_name     TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_sign_in_at TIMESTAMPTZ
);
CREATE OR REPLACE FUNCTION auth.uid() RETURNS UUID LANGUAGE SQL STABLE AS $$ SELECT NULL::UUID $$;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TABLE IF NOT EXISTS public.organizations (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT        NOT NULL,
  slug       TEXT        NOT NULL UNIQUE,
  owner_id   UUID        NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TRIGGER organizations_updated_at
  BEFORE UPDATE ON public.organizations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TABLE IF NOT EXISTS public.contacts (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT        NOT NULL,
  email      TEXT,
  company    TEXT,
  phone      TEXT,
  gstin      TEXT,
  address    TEXT,
  state      TEXT,
  state_code TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.books (
  id                                          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  "Book Title"                                TEXT        NOT NULL,
  "ISBN"                                      TEXT,
  "Product Form"                              TEXT,
  "Language"                                  TEXT,
  "Applicant Type"                            TEXT,
  "Name of Publishing Agency/Publisher"       TEXT,
  "Imprint"                                   TEXT,
  "Name of Author/Editor"                     TEXT,
  "Publication Date"                          TEXT,
  created_at                                  TIMESTAMPTZ DEFAULT NOW(),
  search_vector                               TSVECTOR
    GENERATED ALWAYS AS (
      to_tsvector('simple',
        coalesce("Book Title",                                  '') || ' ' ||
        coalesce("ISBN",                                        '') || ' ' ||
        coalesce("Name of Author/Editor",                      '') || ' ' ||
        coalesce("Name of Publishing Agency/Publisher",        '') || ' ' ||
        coalesce("Imprint",                                    '')
      )
    ) STORED
);
CREATE INDEX IF NOT EXISTS books_search_idx  ON public.books USING gin(search_vector);
CREATE INDEX IF NOT EXISTS books_isbn_idx    ON public.books ("ISBN");
CREATE TABLE IF NOT EXISTS public.profiles (
  id                   UUID    PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  business_name        TEXT,
  business_email       TEXT,
  business_address     TEXT,
  business_phone       TEXT,
  logo_url             TEXT,
  currency             TEXT    DEFAULT 'USD',
  payment_terms        TEXT    DEFAULT 'Net 30',
  invoice_prefix       TEXT    DEFAULT 'INV',
  next_invoice_number  INTEGER DEFAULT 1001,
  created_at           TIMESTAMPTZ DEFAULT NOW(),
  signatory_name       TEXT,
  signature_url        TEXT,
  gstin                TEXT,
  website              TEXT,
  bank_name            TEXT,
  bank_account_number  TEXT,
  bank_ifsc            TEXT,
  bank_branch          TEXT,
  org_id               UUID    REFERENCES public.organizations(id) ON DELETE SET NULL,
  show_book_metadata   BOOLEAN NOT NULL DEFAULT FALSE  
);
CREATE INDEX IF NOT EXISTS idx_profiles_org_id ON public.profiles(org_id);
CREATE TABLE IF NOT EXISTS public.clients (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  org_id     UUID        REFERENCES public.organizations(id) ON DELETE CASCADE,
  name       TEXT        NOT NULL,
  email      TEXT,
  company    TEXT,
  address    TEXT,
  phone      TEXT,
  notes      TEXT,
  gstin      TEXT,
  state      TEXT,
  state_code TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_clients_user_id ON public.clients(user_id);
CREATE INDEX IF NOT EXISTS idx_clients_org_id  ON public.clients(org_id);
CREATE TABLE IF NOT EXISTS public.organization_members (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id    UUID        NOT NULL REFERENCES auth.users(id)           ON DELETE CASCADE,
  role       TEXT        NOT NULL CHECK (role IN ('owner', 'admin', 'staff')),
  invited_by UUID        REFERENCES auth.users(id),
  status     TEXT        NOT NULL DEFAULT 'active'
               CHECK (status IN ('pending', 'active', 'suspended')),
  joined_at  TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_organization_members_org_id  ON public.organization_members(org_id);
CREATE INDEX IF NOT EXISTS idx_organization_members_user_id ON public.organization_members(user_id);
CREATE TABLE IF NOT EXISTS public.organization_invitations (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  email      TEXT        NOT NULL,
  role       TEXT        NOT NULL CHECK (role IN ('admin', 'staff')),
  invited_by UUID        NOT NULL REFERENCES auth.users(id),
  token      TEXT        NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(32), 'hex'),
  status     TEXT        DEFAULT 'pending'
               CHECK (status IN ('pending', 'accepted', 'expired')),
  expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '7 days',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_organization_invitations_org_id ON public.organization_invitations(org_id);
CREATE INDEX IF NOT EXISTS idx_organization_invitations_token  ON public.organization_invitations(token);
CREATE TABLE IF NOT EXISTS public.org_books (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  book_id    UUID        NOT NULL REFERENCES public.books(id)          ON DELETE CASCADE,
  price      NUMERIC(12,2) DEFAULT 0,
  gst_rate   NUMERIC(5,2)  DEFAULT 0,
  stock      INTEGER       DEFAULT 1,
  added_by   UUID        REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_org_books_org_id  ON public.org_books(org_id);
CREATE INDEX IF NOT EXISTS idx_org_books_book_id ON public.org_books(book_id);
CREATE TABLE IF NOT EXISTS public.org_clients (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  contact_id UUID        NOT NULL REFERENCES public.contacts(id)       ON DELETE CASCADE,
  notes      TEXT,
  added_by   UUID        REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_org_clients_org_id     ON public.org_clients(org_id);
CREATE INDEX IF NOT EXISTS idx_org_clients_contact_id ON public.org_clients(contact_id);
CREATE TABLE IF NOT EXISTS public.invoices (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  org_id          UUID        REFERENCES public.organizations(id) ON DELETE CASCADE,
  client_id       UUID        REFERENCES public.clients(id)       ON DELETE SET NULL,
  contact_id      UUID        REFERENCES public.contacts(id)      ON DELETE SET NULL,
  invoice_number  TEXT        NOT NULL,
  status          TEXT        NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft','sent','viewed','paid','overdue','cancelled')),
  issue_date      DATE        NOT NULL DEFAULT CURRENT_DATE,
  subtotal        NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_rate        NUMERIC(5,2)  DEFAULT 0,
  tax_amount      NUMERIC(12,2) DEFAULT 0,
  discount_amount NUMERIC(12,2) DEFAULT 0,
  total           NUMERIC(12,2) NOT NULL DEFAULT 0,
  currency        TEXT          DEFAULT 'INR',
  notes           TEXT,
  terms           TEXT,
  pdf_url         TEXT,
  sent_at         TIMESTAMPTZ,
  viewed_at       TIMESTAMPTZ,
  paid_at         TIMESTAMPTZ,
  supply_type     TEXT          DEFAULT 'IGST'
                    CHECK (supply_type IN ('IGST','CGST_SGST')),
  bill_number     TEXT,
  place_of_supply TEXT,
  order_id        TEXT,
  order_date      DATE,
  created_at      TIMESTAMPTZ   DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   DEFAULT NOW()
);
CREATE TRIGGER invoices_updated_at
  BEFORE UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE INDEX IF NOT EXISTS idx_invoices_user_id   ON public.invoices(user_id);
CREATE INDEX IF NOT EXISTS idx_invoices_org_id    ON public.invoices(org_id);
CREATE INDEX IF NOT EXISTS idx_invoices_client_id ON public.invoices(client_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status    ON public.invoices(status);
CREATE TABLE IF NOT EXISTS public.invoice_items (
  id               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id       UUID          NOT NULL REFERENCES public.invoices(id)      ON DELETE CASCADE,
  org_id           UUID          REFERENCES public.organizations(id)          ON DELETE CASCADE,
  description      TEXT          NOT NULL,
  quantity         NUMERIC(10,2) NOT NULL DEFAULT 1,
  unit_price       NUMERIC(12,2) NOT NULL DEFAULT 0,
  amount           NUMERIC(12,2) NOT NULL DEFAULT 0,
  sort_order       INTEGER       DEFAULT 0,
  hsn_sac          TEXT,
  gst_rate         NUMERIC(5,2)  DEFAULT 0,
  discount_percent NUMERIC(5,2)  DEFAULT 0,
  isbn             TEXT,         
  author           TEXT          
);
CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice_id ON public.invoice_items(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_items_org_id     ON public.invoice_items(org_id);
CREATE TABLE IF NOT EXISTS public.inventory_items (
  id                                    UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                               UUID          REFERENCES auth.users(id) ON DELETE CASCADE,
  org_id                                UUID          REFERENCES public.organizations(id) ON DELETE CASCADE,
  "#"                                   INTEGER,
  "Book Title"                          TEXT          NOT NULL,
  "ISBN"                                TEXT,
  "Product Form"                        TEXT,
  "Language"                            TEXT,
  "Applicant Type"                      TEXT,
  "Name of Publishing Agency/Publisher" TEXT,
  "Imprint"                             TEXT,
  "Name of Author/Editor"               TEXT,
  "Publication Date"                    TEXT,
  price                                 NUMERIC(12,2) DEFAULT 0,
  gst_rate                              NUMERIC(5,2)  DEFAULT 0,
  stock                                 INTEGER       DEFAULT 1,
  created_at                            TIMESTAMPTZ   DEFAULT NOW(),
  search_vector                         TSVECTOR
    GENERATED ALWAYS AS (
      to_tsvector('simple',
        coalesce("Book Title",                                  '') || ' ' ||
        coalesce("ISBN",                                        '') || ' ' ||
        coalesce("Name of Author/Editor",                      '') || ' ' ||
        coalesce("Name of Publishing Agency/Publisher",        '') || ' ' ||
        coalesce("Imprint",                                    '')
      )
    ) STORED
);
CREATE INDEX IF NOT EXISTS inventory_items_search_idx    ON public.inventory_items USING gin(search_vector);
CREATE INDEX IF NOT EXISTS inventory_items_isbn_idx      ON public.inventory_items ("ISBN");
CREATE INDEX IF NOT EXISTS idx_inventory_items_org_id    ON public.inventory_items(org_id);
CREATE TABLE IF NOT EXISTS public.purchase_orders (
  id            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID          NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  org_id        UUID          REFERENCES public.organizations(id) ON DELETE CASCADE,
  order_id      TEXT          NOT NULL UNIQUE,
  client_id     UUID          REFERENCES public.clients(id) ON DELETE SET NULL,
  client_name   TEXT          NOT NULL,
  item_name     TEXT          NOT NULL,
  quantity      NUMERIC(10,2) DEFAULT 1,
  unit_price    NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount  NUMERIC(12,2) NOT NULL DEFAULT 0,
  purchase_date DATE          NOT NULL DEFAULT CURRENT_DATE,
  notes         TEXT,
  status        TEXT          DEFAULT 'completed'
                  CHECK (status IN ('pending','completed','cancelled')),
  created_at    TIMESTAMPTZ   DEFAULT NOW(),
  updated_at    TIMESTAMPTZ   DEFAULT NOW()
);
CREATE OR REPLACE FUNCTION generate_purchase_order_id()
RETURNS TRIGGER AS $$
BEGIN
  NEW.order_id := 'PO-' ||
    TO_CHAR(NOW(), 'YYYY') || '-' ||
    LPAD(FLOOR(RANDOM() * 900000 + 100000)::TEXT, 6, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER set_purchase_order_id
  BEFORE INSERT ON public.purchase_orders
  FOR EACH ROW
  WHEN (NEW.order_id IS NULL OR NEW.order_id = '')
  EXECUTE FUNCTION generate_purchase_order_id();
CREATE TRIGGER purchase_orders_updated_at
  BEFORE UPDATE ON public.purchase_orders
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE INDEX IF NOT EXISTS purchase_orders_org_date_idx  ON public.purchase_orders(org_id, purchase_date DESC);
CREATE INDEX IF NOT EXISTS purchase_orders_user_date_idx ON public.purchase_orders(user_id, purchase_date DESC);
CREATE TABLE IF NOT EXISTS public.notifications (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  org_id     UUID        REFERENCES public.organizations(id) ON DELETE CASCADE,
  type       TEXT        NOT NULL
               CHECK (type IN ('invoice_viewed','payment_received','invoice_overdue')),
  title      TEXT        NOT NULL,
  message    TEXT        NOT NULL,
  invoice_id UUID        REFERENCES public.invoices(id) ON DELETE CASCADE,
  is_read    BOOLEAN     DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_notifications_org_id      ON public.notifications(org_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id     ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON public.notifications(user_id, is_read)
  WHERE is_read = false;
CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id          UUID     PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  invoice_viewed   BOOLEAN  DEFAULT true,
  payment_received BOOLEAN  DEFAULT true,
  invoice_overdue  BOOLEAN  DEFAULT true,
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);
CREATE OR REPLACE FUNCTION public.get_user_org_id(user_uuid UUID)
RETURNS UUID
LANGUAGE SQL
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT org_id
  FROM   organization_members
  WHERE  user_id = user_uuid
    AND  status  = 'active'
  LIMIT 1;
$$;
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, business_email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS party_type       TEXT          NOT NULL DEFAULT 'customer',
  ADD COLUMN IF NOT EXISTS credit_days      INTEGER       NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS credit_limit     NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS opening_balance  NUMERIC(12,2) NOT NULL DEFAULT 0,  
  ADD COLUMN IF NOT EXISTS pincode          TEXT,
  ADD COLUMN IF NOT EXISTS shipping_address TEXT,
  ADD COLUMN IF NOT EXISTS shipping_state   TEXT,
  ADD COLUMN IF NOT EXISTS shipping_pincode TEXT;
ALTER TABLE public.clients DROP CONSTRAINT IF EXISTS clients_party_type_check;
ALTER TABLE public.clients ADD CONSTRAINT clients_party_type_check
  CHECK (party_type IN ('customer', 'supplier', 'binder', 'both'));
ALTER TABLE public.clients DROP CONSTRAINT IF EXISTS clients_credit_days_check;
ALTER TABLE public.clients ADD CONSTRAINT clients_credit_days_check
  CHECK (credit_days >= 0);
CREATE INDEX IF NOT EXISTS idx_clients_org_party_type ON public.clients(org_id, party_type);
ALTER TABLE public.inventory_items
  ADD COLUMN IF NOT EXISTS binding       TEXT,
  ADD COLUMN IF NOT EXISTS purchase_rate NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_stock     INTEGER       NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS damaged_stock INTEGER       NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hsn_code      TEXT;
ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS doc_type               TEXT          NOT NULL DEFAULT 'sales_invoice',
  ADD COLUMN IF NOT EXISTS payment_mode           TEXT          NOT NULL DEFAULT 'credit',
  ADD COLUMN IF NOT EXISTS party_name             TEXT,
  ADD COLUMN IF NOT EXISTS party_phone            TEXT,
  ADD COLUMN IF NOT EXISTS credit_days            INTEGER       NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS due_date               DATE,
  ADD COLUMN IF NOT EXISTS billing_address        TEXT,
  ADD COLUMN IF NOT EXISTS shipping_name          TEXT,
  ADD COLUMN IF NOT EXISTS shipping_address       TEXT,
  ADD COLUMN IF NOT EXISTS extra_discount_type    TEXT          NOT NULL DEFAULT 'percent',
  ADD COLUMN IF NOT EXISTS extra_discount_value   NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS postage_charge         NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_charges          NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_charges_label    TEXT,
  ADD COLUMN IF NOT EXISTS apply_round_off        BOOLEAN       NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS round_off              NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_paid            NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS source_doc_id          UUID          REFERENCES public.invoices(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS party_ref_number       TEXT,
  ADD COLUMN IF NOT EXISTS party_ref_date         DATE,
  ADD COLUMN IF NOT EXISTS affects_stock          BOOLEAN       NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS valid_until            DATE,
  ADD COLUMN IF NOT EXISTS reason                 TEXT,
  ADD COLUMN IF NOT EXISTS approval_status        TEXT,
  ADD COLUMN IF NOT EXISTS approved_by            UUID          REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS approved_at            TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS rejection_reason       TEXT,
  
  ADD COLUMN IF NOT EXISTS dispatch_mode          TEXT          NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS delivery_status        TEXT          NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS courier_name           TEXT,
  ADD COLUMN IF NOT EXISTS tracking_number        TEXT,
  ADD COLUMN IF NOT EXISTS dispatch_date          DATE,
  ADD COLUMN IF NOT EXISTS expected_delivery_date DATE,
  ADD COLUMN IF NOT EXISTS delivered_date         DATE,
  
  ADD COLUMN IF NOT EXISTS transport_name         TEXT,
  ADD COLUMN IF NOT EXISTS lr_number              TEXT,
  ADD COLUMN IF NOT EXISTS vehicle_number         TEXT,
  ADD COLUMN IF NOT EXISTS cartons                INTEGER,
  ADD COLUMN IF NOT EXISTS freight_type           TEXT,
  ADD COLUMN IF NOT EXISTS delivery_type          TEXT,
  ADD COLUMN IF NOT EXISTS transport_details      TEXT;
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_status_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_status_check
  CHECK (status IN ('draft', 'sent', 'viewed', 'paid', 'overdue', 'cancelled', 'converted'));
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_doc_type_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_doc_type_check
  CHECK (doc_type IN (
    'sales_invoice', 'estimate', 'delivery_challan', 'sales_return', 'credit_note',
    'purchase_bill', 'purchase_return', 'debit_note', 'binding_order'
  ));
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_payment_mode_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_payment_mode_check
  CHECK (payment_mode IN ('cash', 'credit'));
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_extra_discount_type_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_extra_discount_type_check
  CHECK (extra_discount_type IN ('percent', 'amount'));
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_charges_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_charges_check
  CHECK (extra_discount_value >= 0 AND postage_charge >= 0 AND other_charges >= 0 AND credit_days >= 0);
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_dispatch_mode_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_dispatch_mode_check
  CHECK (dispatch_mode IN ('none', 'courier', 'transport', 'hand'));
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_delivery_status_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_delivery_status_check
  CHECK (delivery_status IN ('pending', 'dispatched', 'in_transit', 'delivered', 'returned'));
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_freight_type_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_freight_type_check
  CHECK (freight_type IS NULL OR freight_type IN ('paid', 'to_pay'));
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_delivery_type_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_delivery_type_check
  CHECK (delivery_type IS NULL OR delivery_type IN ('door', 'godown'));
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_approval_status_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_approval_status_check
  CHECK (approval_status IS NULL OR approval_status IN ('pending', 'approved', 'rejected'));
CREATE INDEX IF NOT EXISTS idx_invoices_org_doc_date ON public.invoices(org_id, doc_type, issue_date DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_org_client   ON public.invoices(org_id, client_id);
CREATE INDEX IF NOT EXISTS idx_invoices_source_doc   ON public.invoices(source_doc_id);
CREATE INDEX IF NOT EXISTS idx_invoices_due_date     ON public.invoices(org_id, due_date);
UPDATE public.invoices
SET credit_days = substring(terms FROM 'Net\s*(\d+)')::INTEGER
WHERE terms ~ 'Net\s*\d+' AND credit_days = 0;
UPDATE public.invoices
SET due_date = issue_date + credit_days
WHERE due_date IS NULL;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.invoices
    GROUP BY org_id, doc_type, invoice_number
    HAVING COUNT(*) > 1
  ) THEN
    CREATE UNIQUE INDEX IF NOT EXISTS uq_invoices_org_doc_number
      ON public.invoices(org_id, doc_type, invoice_number);
  ELSE
    RAISE NOTICE 'Duplicate document numbers found — unique index uq_invoices_org_doc_number not created';
  END IF;
END $$;
ALTER TABLE public.invoice_items
  ADD COLUMN IF NOT EXISTS item_id     UUID          REFERENCES public.inventory_items(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS binding     TEXT,
  ADD COLUMN IF NOT EXISTS damaged_qty NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE public.invoice_items DROP CONSTRAINT IF EXISTS invoice_items_damaged_qty_check;
ALTER TABLE public.invoice_items ADD CONSTRAINT invoice_items_damaged_qty_check
  CHECK (damaged_qty >= 0 AND damaged_qty <= quantity);
CREATE INDEX IF NOT EXISTS idx_invoice_items_item_id ON public.invoice_items(item_id);
CREATE TABLE IF NOT EXISTS public.number_series (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id       UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  doc_type     TEXT        NOT NULL,
  prefix       TEXT        NOT NULL,
  next_number  INTEGER     NOT NULL DEFAULT 1 CHECK (next_number > 0),
  include_year BOOLEAN     NOT NULL DEFAULT TRUE,
  updated_at   TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (org_id, doc_type)
);
DROP TRIGGER IF EXISTS number_series_updated_at ON public.number_series;
CREATE TRIGGER number_series_updated_at
  BEFORE UPDATE ON public.number_series
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
INSERT INTO public.number_series (org_id, doc_type, prefix, next_number)
SELECT o.id, 'sales_invoice',
       COALESCE(NULLIF(p.invoice_prefix, ''), 'INV'),
       GREATEST(COALESCE(p.next_invoice_number, 1001), 1)
FROM public.organizations o
LEFT JOIN public.profiles p ON p.id = o.owner_id
ON CONFLICT (org_id, doc_type) DO NOTHING;
CREATE TABLE IF NOT EXISTS public.payments (
  id             UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id         UUID          NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id        UUID          NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id      UUID          REFERENCES public.clients(id)  ON DELETE SET NULL,
  invoice_id     UUID          REFERENCES public.invoices(id) ON DELETE SET NULL,
  direction      TEXT          NOT NULL CHECK (direction IN ('in', 'out')),
  payment_number TEXT,
  amount         NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  payment_date   DATE          NOT NULL DEFAULT CURRENT_DATE,
  mode           TEXT          NOT NULL DEFAULT 'cash'
                   CHECK (mode IN ('cash', 'upi', 'bank', 'cheque', 'card', 'other')),
  reference      TEXT,
  notes          TEXT,
  created_at     TIMESTAMPTZ   DEFAULT NOW(),
  updated_at     TIMESTAMPTZ   DEFAULT NOW()
);
DROP TRIGGER IF EXISTS payments_updated_at ON public.payments;
CREATE TRIGGER payments_updated_at
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE INDEX IF NOT EXISTS idx_payments_org_date   ON public.payments(org_id, payment_date DESC);
CREATE INDEX IF NOT EXISTS idx_payments_client     ON public.payments(client_id);
CREATE INDEX IF NOT EXISTS idx_payments_invoice    ON public.payments(invoice_id);
INSERT INTO public.payments (org_id, user_id, client_id, invoice_id, direction, amount, payment_date, mode, notes)
SELECT i.org_id, i.user_id, i.client_id, i.id, 'in', i.total,
       COALESCE(i.paid_at::DATE, i.issue_date), 'other',
       'Recorded automatically: invoice was marked paid'
FROM public.invoices i
WHERE i.status = 'paid'
  AND i.total > 0
  AND i.org_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM public.payments p WHERE p.invoice_id = i.id);
UPDATE public.invoices SET amount_paid = total WHERE status = 'paid';
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id             UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id         UUID          NOT NULL REFERENCES public.organizations(id)   ON DELETE CASCADE,
  item_id        UUID          NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
  doc_id         UUID          REFERENCES public.invoices(id) ON DELETE CASCADE,
  doc_type       TEXT          NOT NULL,  
  movement_date  DATE          NOT NULL DEFAULT CURRENT_DATE,
  qty_change     INTEGER       NOT NULL DEFAULT 0,  
  damaged_change INTEGER       NOT NULL DEFAULT 0,  
  rate           NUMERIC(12,2) NOT NULL DEFAULT 0,
  reason         TEXT,
  user_id        UUID          REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ   DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_stock_movements_item ON public.stock_movements(item_id, movement_date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_movements_doc  ON public.stock_movements(doc_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_org  ON public.stock_movements(org_id, movement_date DESC);
INSERT INTO public.stock_movements (org_id, item_id, doc_type, movement_date, qty_change, rate, reason, user_id)
SELECT ii.org_id, ii.id, 'opening', COALESCE(ii.created_at::DATE, CURRENT_DATE),
       COALESCE(ii.stock, 0), COALESCE(ii.price, 0), 'Opening stock', ii.user_id
FROM public.inventory_items ii
WHERE ii.org_id IS NOT NULL
  AND COALESCE(ii.stock, 0) <> 0
  AND NOT EXISTS (SELECT 1 FROM public.stock_movements sm WHERE sm.item_id = ii.id);
ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_type_check
  CHECK (type IN ('invoice_viewed', 'payment_received', 'invoice_overdue', 'approval_pending'));
ALTER TABLE public.invoice_items
  ADD COLUMN IF NOT EXISTS binding_charge NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE public.invoice_items DROP CONSTRAINT IF EXISTS invoice_items_binding_charge_check;
ALTER TABLE public.invoice_items ADD CONSTRAINT invoice_items_binding_charge_check
  CHECK (binding_charge >= 0);
ALTER TABLE public.inventory_items
  ADD COLUMN IF NOT EXISTS binding_charge NUMERIC(12,2) NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS public.binding_rates (
  id         UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     UUID          NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name       TEXT          NOT NULL,
  charge     NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (charge >= 0),
  sort_order INTEGER       NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ   DEFAULT NOW(),
  updated_at TIMESTAMPTZ   DEFAULT NOW(),
  UNIQUE (org_id, name)
);
DROP TRIGGER IF EXISTS binding_rates_updated_at ON public.binding_rates;
CREATE TRIGGER binding_rates_updated_at
  BEFORE UPDATE ON public.binding_rates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE INDEX IF NOT EXISTS idx_binding_rates_org ON public.binding_rates(org_id, sort_order);